apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mon-service
  template:
    metadata:
      labels:
        app: mon-service
    spec:
      containers:
        - name: api
          image: mon-service:1.1
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: db